version: '3'

networks:
    gof-network:
        driver: bridge

services:

#gof-db
    gof-db:
        image: mysql:5.7
        container_name: gof-db
        restart: always
        ports:
            - "${DB_PORT:-39906}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-gof}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Taipei}
        command: [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_general_ci",
            "--innodb-use-native-aio=0",
            "--server-id=1",
            "--log_bin=ON",
            "--default-authentication-plugin=mysql_native_password"
        ]
        volumes:
            - ./dockerize/data/mysql:/var/lib/mysql
        networks:
            - gof-network
            
#gof-redis
    gof-redis:
        build:
            context: .
            dockerfile: ./dockerize/dockerfile/redis.dockerfile
        image: danielhuang-030/gof-redis:0.0.1
        container_name: gof-redis
        restart: always
        volumes:
            - ./dockerize/data/redis:/data
        networks:
            - gof-network
            
#phpMyAdmin
    gof-pma:
        image: phpmyadmin/phpmyadmin:latest
        container_name: gof-pma
        restart: always
        volumes:
            - ./dockerize/conf/phpMyAdmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        ports:
            - "${PMA_PORT:-39901}:80"
        environment:
            SESSION_TIMEOUT: ${PMA_SESSION_TIMEOUT:-86400}
            PMA_HOST: gof-db
        networks:
            - gof-network
        depends_on:
            - gof-db
            
#phpRedisAdmin
    gof-pra:
        image: erikdubbelboer/phpredisadmin:latest
        container_name: gof-pra
        restart: always
        volumes:
            - ./dockerize/conf/phpRedisAdmin/config.sample.inc.php:/src/app/includes/config.sample.inc.php
        ports:
            - "${PRA_PORT:-39902}:80"
        environment:
            REDIS_1_HOST: ${REDIS_HOST:-gof-redis}
            REDIS_1_NAME: ${REDIS_HOST:-gof-redis}
        networks:
            - gof-network
        depends_on:
            - gof-redis

#gof
    gof:
        build:
            context: .
            dockerfile: ./dockerize/dockerfile/app.dockerfile
        image: danielhuang-030/gof:0.0.1
        container_name: gof
        restart: always
        volumes: 
          - ./app:/usr/app
        command: air
        ports:
            - "${WEB_PORT:-39900}:8199"
        networks:
            - gof-network
        depends_on:
            - gof-db
            - gof-redis
