version: '3'

networks:
    golang-network:
        driver: bridge

services:

#golang-db
    golang-db:
        image: mysql:5.7
        container_name: ${DB_HOST:-golang-db}
        restart: always
        ports:
            - "${DB_PORT:-30106}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-golang}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Taipei}
        command: [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_general_ci",
            "--innodb-use-native-aio=0",
            "--server-id=1",
            "--log_bin=ON",
            "--default-authentication-plugin=mysql_native_password"
        ]
        volumes:
            - ./dockerize/data/mysql:/var/lib/mysql
        networks:
            - golang-network

#golang-redis
    golang-redis:
        image: redis:latest
        container_name: ${REDIS_HOST:-golang-redis}
        restart: always
        volumes:
            - ./dockerize/data/redis:/data
        ports:
            - "${REDIS_PORT:-30109}:6379"
        environment:
            - TZ=${TZ:-Asia/Taipei}
            - LANG=en_US.UTF-8
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
        networks:
            - golang-network

#phpMyAdmin
    golang-pma:
        image: phpmyadmin/phpmyadmin:latest
        container_name: golang-pma
        restart: always
        volumes:
            - ./dockerize/conf/phpMyAdmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        ports:
            - "${PMA_PORT:-30110}:80"
        environment:
            SESSION_TIMEOUT: ${PMA_SESSION_TIMEOUT:-86400}
            PMA_HOST: ${DB_HOST:-golang-db}
        networks:
            - golang-network
        depends_on:
            - ${DB_HOST:-golang-db}

#phpRedisAdmin
    golang-pra:
        image: erikdubbelboer/phpredisadmin:latest
        container_name: golang-pra
        restart: always
        volumes:
            - ./dockerize/conf/phpRedisAdmin/config.sample.inc.php:/src/app/includes/config.sample.inc.php
        ports:
            - "${PRA_PORT:-30120}:80"
        environment:
            REDIS_1_HOST: ${REDIS_HOST:-golang-redis}
            REDIS_1_NAME: ${REDIS_HOST:-golang-redis}
        networks:
            - golang-network
        depends_on:
            - ${REDIS_HOST:-golang-redis}

#golang-app
    golang-app:
        build:
            context: .
            dockerfile: ./dockerize/dockerfile/app.dockerfile
        image: danielhuang-030/golang:0.0.2
        container_name: ${APP:-golang-app}
        restart: always
        volumes:
          - ./app:/usr/app
        command: air
        ports:
            - "${WEB_PORT:-30100}:8199"
        networks:
            - golang-network
        depends_on:
            - ${DB_HOST:-golang-db}
            - ${REDIS_HOST:-golang-redis}
