version: '3.7'

networks:
    golang-network:
        driver: bridge

services:

#golang-db
    golang-db:
        image: mysql:8.0
        container_name: ${DB_HOST:-golang-db}
        restart: always
        ports:
            - "${DB_PORT:-30106}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-golang}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Taipei}
        command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci", "--log-bin", "--binlog-format=ROW"]
        volumes:
            - ./dockerize/data/mysql:/var/lib/mysql
        networks:
            - golang-network

#golang-redis
    golang-redis:
        image: redis:6
        container_name: ${REDIS_HOST:-golang-redis}
        restart: always
        volumes:
            - ./dockerize/data/redis:/data
        ports:
            - "${REDIS_PORT:-30109}:6379"
        environment:
            - TZ=${TZ:-Asia/Taipei}
            - LANG=en_US.UTF-8
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
        networks:
            - golang-network

#phpMyAdmin
    golang-pma:
        image: phpmyadmin/phpmyadmin:5.2
        container_name: golang-pma
        restart: always
        volumes:
            - ./dockerize/conf/phpMyAdmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        ports:
            - "${PMA_PORT:-30110}:80"
        environment:
            SESSION_TIMEOUT: ${PMA_SESSION_TIMEOUT:-86400}
            PMA_HOST: ${DB_HOST:-golang-db}
            PMA_USER: root
            PMA_PASSWORD: ${DB_ROOT_PASSWORD:-root}
        networks:
            - golang-network
        depends_on:
            - ${DB_HOST:-golang-db}

#phpRedisAdmin
    golang-pra:
        image: erikdubbelboer/phpredisadmin:1.19
        container_name: golang-pra
        restart: always
        volumes:
            - ./dockerize/conf/phpRedisAdmin/config.sample.inc.php:/src/app/includes/config.sample.inc.php
        ports:
            - "${PRA_PORT:-30120}:80"
        environment:
            REDIS_1_HOST: ${REDIS_HOST:-golang-redis}
            REDIS_1_NAME: ${REDIS_HOST:-golang-redis}
        networks:
            - golang-network
        depends_on:
            - ${REDIS_HOST:-golang-redis}

#golang-app
    golang-app:
        build:
            context: .
            dockerfile: ./dockerize/dockerfile/app.dockerfile
        image: danielhuang-030/golang:0.0.3
        container_name: ${APP:-golang-app}
        restart: always
        volumes:
          - ./app:/app
        ports:
            - "${WEB_PORT:-30100}:8199"
        networks:
            - golang-network
        depends_on:
            - ${DB_HOST:-golang-db}
            - ${REDIS_HOST:-golang-redis}
